fixtures:
  repositories:
    "apt": "git://github.com/a420478805/puppetlabs-apt.git"
    "keystone": "git://github.com/a420478805/puppetlabs-keystone.git"
    "mysql": "git://github.com/a420478805/puppetlabs-mysql.git"
    "nova": "git://github.com/a420478805/puppetlabs-nova.git"
    "stdlib": "git://github.com/a420478805/puppetlabs-stdlib.git"
    "sysctl": "git://github.com/duritong/puppet-sysctl.git"
  symlinks:
    "openstack": "#{source_dir}"
